services:
  - type: web
    name: earncashio-backend
    env: node
    plan: free
    buildCommand: npm --prefix server install
    startCommand: npm --prefix server start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
